import { Center, Flex, Heading, Text } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <Center h="100vh">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="column" alignItems="center">
        <Heading mb={4}>What is this?</Heading>
        <Text>
          I am pretty horrible at styling things with CSS so have been enjoying trying
          out things like Chakra UI and Tailwind. This is a little NextJS based app to
          put all the examples I've done.
        </Text>
      </Flex>
    </Center>
  )
}
